---
name: "Build App Dumper"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PS4 Payload SDK"
        run: |
          git clone https://github.com/Scene-Collective/ps4-payload-sdk.git "$HOME/ps4-payload-sdk"
          cd "$HOME/ps4-payload-sdk"
          chmod +x install.sh
          sudo ./install.sh

      - name: "Build App Dumper"
        run: |
          export PS4SDK=/lib/ps4-payload-sdk
          make

      - name: "Upload Binary"
        uses: actions/upload-artifact@v4
        with:
          name: app-dumper-bin
          path: ./*.bin
          if-no-files-found: error

      - name: "Upload Map"
        uses: actions/upload-artifact@v4
        with:
          name: app-dumper-map
          path: ./*.map
          if-no-files-found: ignore
