---
name: "Sanity Check"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Build with PS4 Payload SDK"
        uses: Scene-Collective/ps4-payload-sdk@46efae9
        with:
          app_path: .
          build_command: make

      - name: "Upload Binary Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: app-dumper-bin
          path: ./*.bin
          if-no-files-found: error

      - name: "Upload Map Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: app-dumper-map
          path: ./*.map
          if-no-files-found: error
